package io.kscriptx.pack

/**
 * Generates the GraalVM `@CEntryPoint` bridge so user scripts need no annotations.
 * Symbols: `kscriptx_create_isolate`, `kscriptx_tear_down_isolate`, `kscriptx_run`.
 */
object NativeBridgeGenerator {
    const val BRIDGE_PACKAGE = "io.kscriptx.nativebridge"
    const val BRIDGE_CLASS = "KscriptxNativeBridge"
    const val BRIDGE_FQCN = "$BRIDGE_PACKAGE.$BRIDGE_CLASS"

    /** HotSpot-side JNI facade FQCN (loads the shared library). */
    const val LOADER_PACKAGE = "io.kscriptx.shared"
    const val LOADER_CLASS = "SharedLibLoader"
    const val LOADER_FQCN = "$LOADER_PACKAGE.$LOADER_CLASS"

    fun bridgeJavaSource(entryPointFqcn: String): String {
        val escaped = entryPointFqcn.replace("\"", "\\\"")
        return """
            |package $BRIDGE_PACKAGE;
            |
            |import org.graalvm.nativeimage.IsolateThread;
            |import org.graalvm.nativeimage.c.function.CEntryPoint;
            |import org.graalvm.nativeimage.c.type.CCharPointer;
            |import org.graalvm.nativeimage.c.type.CCharPointerPointer;
            |import org.graalvm.nativeimage.c.type.CTypeConversion;
            |
            |/**
            | * Generated by kscriptx — do not edit.
            | * Entry point class: $escaped
            | */
            |public final class $BRIDGE_CLASS {
            |    private $BRIDGE_CLASS() {}
            |
            |    @CEntryPoint(name = "kscriptx_create_isolate", builtin = CEntryPoint.Builtin.CREATE_ISOLATE)
            |    public static IsolateThread createIsolate() {
            |        return null; // builtin — body ignored
            |    }
            |
            |    @CEntryPoint(name = "kscriptx_tear_down_isolate", builtin = CEntryPoint.Builtin.TEAR_DOWN_ISOLATE)
            |    public static int tearDownIsolate(IsolateThread thread) {
            |        return 0; // builtin — body ignored
            |    }
            |
            |    @CEntryPoint(name = "kscriptx_run")
            |    public static int run(IsolateThread thread, int argc, CCharPointerPointer argv) {
            |        try {
            |            String[] args = new String[Math.max(0, argc)];
            |            for (int i = 0; i < args.length; i++) {
            |                CCharPointer p = argv.read(i);
            |                args[i] = CTypeConversion.toJavaString(p);
            |            }
            |            Class<?> mainCl = Class.forName("$escaped");
            |            java.lang.reflect.Method main = mainCl.getMethod("main", String[].class);
            |            main.invoke(null, (Object) args);
            |            return 0;
            |        } catch (Throwable t) {
            |            t.printStackTrace();
            |            return 1;
            |        }
            |    }
            |}
            """.trimMargin() + "\n"
    }

    fun loaderJavaSource(libBaseName: String): String {
        // libBaseName without lib prefix / extension, for System.loadLibrary
        val loadName = libBaseName.removePrefix("lib")
        return """
            |package $LOADER_PACKAGE;
            |
            |/**
            | * Generated by kscriptx — HotSpot loader for GraalVM native shared library.
            | * Loads native library "$loadName" (lib$loadName.so / .dylib / .dll).
            | */
            |public final class $LOADER_CLASS {
            |    static {
            |        String explicit = System.getProperty("kscriptx.shared.lib");
            |        if (explicit != null && !explicit.isBlank()) {
            |            System.load(explicit);
            |        } else {
            |            System.loadLibrary("$loadName");
            |        }
            |    }
            |
            |    /** Portable isolate thread id from Native Image. */
            |    public static native long kscriptx_create_isolate();
            |
            |    public static native int kscriptx_tear_down_isolate(long isolateThread);
            |
            |    public static native int kscriptx_run(long isolateThread, int argc, long argvIgnored);
            |
            |    public static void main(String[] args) {
            |        long iso = 0L;
            |        try {
            |            iso = createIsolateCompat();
            |            int code = runCompat(iso, args);
            |            System.exit(code);
            |        } catch (UnsatisfiedLinkError e) {
            |            System.err.println("Failed to load kscriptx shared library '$loadName': " + e.getMessage());
            |            System.err.println("Set -Djava.library.path=... or -Dkscriptx.shared.lib=/absolute/path/to/lib");
            |            e.printStackTrace();
            |            System.exit(2);
            |        } finally {
            |            if (iso != 0L) {
            |                try { tearDownCompat(iso); } catch (Throwable ignored) {}
            |            }
            |        }
            |    }
            |
            |    // HotSpot cannot call CREATE_ISOLATE builtins via arbitrary native names easily
            |    // without matching JNI stubs. The C runner (Phase 2) is the supported entry;
            |    // this loader documents the library and supports System.load for tooling.
            |    private static long createIsolateCompat() {
            |        try {
            |            return kscriptx_create_isolate();
            |        } catch (UnsatisfiedLinkError e) {
            |            throw e;
            |        }
            |    }
            |
            |    private static int runCompat(long iso, String[] args) {
            |        // argv marshalling requires a native helper; for JVM hosting prefer the
            |        // generated C runner (--native-runner) or full --native executable.
            |        System.err.println(
            |            "SharedLibLoader: invoke the C runner (kscriptx --native-shared --native-runner) " +
            |            "or use --native for a standalone executable. " +
            |            "Loaded isolate=" + iso + " args=" + args.length);
            |        return tearDownCompat(iso) == 0 ? 0 : 1;
            |    }
            |
            |    private static int tearDownCompat(long iso) {
            |        try {
            |            return kscriptx_tear_down_isolate(iso);
            |        } catch (UnsatisfiedLinkError e) {
            |            return 0;
            |        }
            |    }
            |
            |    private $LOADER_CLASS() {}
            |}
            """.trimMargin() + "\n"
    }

    fun runnerCSource(stem: String, headerName: String): String = """
        |/* Generated by kscriptx — thin runner for lib$stem shared image. */
        |#include <stdio.h>
        |#include <stdlib.h>
        |#include "$headerName"
        |
        |int main(int argc, char** argv) {
        |    graal_isolatethread_t* thread = kscriptx_create_isolate();
        |    if (thread == NULL) {
        |        fprintf(stderr, "kscriptx: failed to create native isolate\n");
        |        return 2;
        |    }
        |    int code = kscriptx_run(thread, argc, argv);
        |    kscriptx_tear_down_isolate(thread);
        |    return code;
        |}
        """.trimMargin() + "\n"
}