#!/usr/bin/env python3
"""Generate a Cursor canvas from bench-compare.json.

Usage:
  ./scripts/gen-bench-canvas.py [compare.json] [out.canvas.tsx]

Defaults:
  compare.json  -> build/reports/perf-compare/compare.json
  canvas        -> $CANVAS_DIR/kscript-vs-kscriptx.canvas.tsx
                  or ~/.cursor/projects/p-kscript3/canvases/...

Re-run after every ./scripts/bench-compare.sh to refresh charts/tables.
"""
from __future__ import annotations

import json
import os
import sys
from pathlib import Path


def repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def default_json() -> Path:
    return repo_root() / "build" / "reports" / "perf-compare" / "compare.json"


def default_canvas() -> Path:
    env = os.environ.get("CANVAS_DIR")
    if env:
        return Path(env) / "kscript-vs-kscriptx.canvas.tsx"
    candidates = [
        Path.home() / ".cursor" / "projects" / "p-kscript3" / "canvases",
        Path("/home/z/.cursor/projects/p-kscript3/canvases"),
    ]
    for c in candidates:
        if c.is_dir():
            return c / "kscript-vs-kscriptx.canvas.tsx"
    return repo_root() / "build" / "reports" / "perf-compare" / "kscript-vs-kscriptx.canvas.tsx"


def fmt_ms(v: float | None) -> str:
    if v is None:
        return "—"
    if v >= 1000:
        return f"{v / 1000:.2f}s"
    return f"{v:.0f} ms"


def speedup(a: float | None, b: float | None) -> str:
    if a is None or b is None or b == 0:
        return "—"
    return f"{a / b:.2f}×"


def j(s: object) -> str:
    return json.dumps(s, ensure_ascii=False)


def build_tsx(doc: dict) -> str:
    results = doc.get("results") or []
    if not results:
        raise SystemExit("compare.json has no results — run scripts/bench-compare.sh first")

    tools = doc.get("tools") or {}
    ks = tools.get("kscript") or {}
    kx = tools.get("kscriptx") or {}
    host = doc.get("host") or {}
    phases_help = doc.get("phases_help") or {}

    categories: list[str] = []
    series_ks: list[float] = []
    series_kx: list[float] = []
    series_daemon: list[float] = []
    table_rows: list[list[str]] = []
    desc_rows: list[list[str]] = []

    best_warm_speedup: float | None = None
    median_warm_kx: list[float] = []

    for r in results:
        rid = r.get("id", "?")
        label = r.get("label", rid)
        desc_rows.append([rid, label, r.get("script", ""), r.get("description", "")])
        phases = r.get("phases") or {}
        for phase, pname in (("cold", "cold"), ("warm", "warm"), ("warm_daemon", "daemon")):
            p = phases.get(phase) or {}
            ks_ms = p.get("kscript_ms")
            kx_ms = p.get("kscriptx_ms")
            if phase == "warm_daemon":
                categories.append(f"{rid} / daemon")
                series_ks.append(0.0)
                series_kx.append(0.0)
                series_daemon.append(float(kx_ms) if kx_ms is not None else 0.0)
                table_rows.append([rid, "warm + daemon", "—", "—", fmt_ms(kx_ms), "—"])
            else:
                categories.append(f"{rid} / {pname}")
                series_ks.append(float(ks_ms) if ks_ms is not None else 0.0)
                series_kx.append(float(kx_ms) if kx_ms is not None else 0.0)
                series_daemon.append(0.0)
                table_rows.append(
                    [rid, pname, fmt_ms(ks_ms), fmt_ms(kx_ms), "—", speedup(ks_ms, kx_ms)]
                )
                if phase == "warm" and ks_ms and kx_ms:
                    sp = ks_ms / kx_ms
                    if best_warm_speedup is None or sp > best_warm_speedup:
                        best_warm_speedup = sp
                if phase == "warm" and kx_ms is not None:
                    median_warm_kx.append(float(kx_ms))

    warm_kx_avg = sum(median_warm_kx) / len(median_warm_kx) if median_warm_kx else None
    cases_n = len(results)
    generated = doc.get("generated_at", "")
    warm_runs = doc.get("warm_runs", "?")
    best_stat = f"{best_warm_speedup:.2f}×" if best_warm_speedup is not None else "—"
    avg_stat = fmt_ms(warm_kx_avg)

    phase_help_rows = [[k, v] for k, v in phases_help.items()]
    ks_path = ks.get("path") or "(skipped)"
    ks_ver = ks.get("version") or "n/a"
    kx_path = kx.get("path") or ""
    kx_ver = kx.get("version") or "n/a"
    footer = (
        "Host: "
        + str(host.get("os", "unknown"))
        + " · "
        + str(host.get("java_version", "unknown"))
        + " · kscript: "
        + str(ks_path)
        + " ("
        + str(ks_ver)
        + ") · kscriptx: "
        + str(kx_path)
        + " ("
        + str(kx_ver)
        + ")"
    )

    return f"""\
import {{
  BarChart,
  Callout,
  Card,
  CardBody,
  CardHeader,
  Divider,
  Grid,
  H1,
  H2,
  Stack,
  Stat,
  Table,
  Text,
}} from "cursor/canvas";

/**
 * Auto-generated by scripts/gen-bench-canvas.py — do not edit by hand.
 * Refresh: ./scripts/bench-compare.sh
 *      or: ./scripts/gen-bench-canvas.py build/reports/perf-compare/compare.json
 */
const GENERATED_AT = {j(generated)};
const WARM_RUNS = {j(str(warm_runs))};
const CATEGORIES = {j(categories)};
const SERIES_KSCRIPT = {j(series_ks)};
const SERIES_KSCRIPTX = {j(series_kx)};
const SERIES_DAEMON = {j(series_daemon)};
const RESULT_ROWS = {j(table_rows)};
const CASE_ROWS = {j(desc_rows)};
const PHASE_ROWS = {j(phase_help_rows)};

export default function KscriptVsKscriptxBench() {{
  return (
    <Stack gap={{20}}>
      <Stack gap={{6}}>
        <H1>kscript vs kscriptx</H1>
        <Text tone="secondary">
          Wall-clock script run times (resolve + compile + execute). Warm values are
          the median of {{WARM_RUNS}} samples. Source: scripts/bench-compare.sh · {{GENERATED_AT}}
        </Text>
      </Stack>

      <Grid columns={{4}} gap={{16}}>
        <Stat value={j(str(cases_n))} label="Cases measured" />
        <Stat value={j(best_stat)} label="Best warm speedup (kscript / kscriptx)" tone="success" />
        <Stat value={j(avg_stat)} label="Avg warm kscriptx" />
        <Stat value={j("yes" if kx.get("native_kotlinc") else "no")} label="Native kotlinc" />
      </Grid>

      <Card>
        <CardHeader>Latency by case and phase (ms)</CardHeader>
        <CardBody>
          <BarChart
            categories={{CATEGORIES}}
            series={{[
              {{ name: "kscript", data: SERIES_KSCRIPT, tone: "neutral" }},
              {{ name: "kscriptx (no daemon)", data: SERIES_KSCRIPTX, tone: "info" }},
              {{ name: "kscriptx daemon", data: SERIES_DAEMON, tone: "success" }},
            ]}}
            height={{320}}
            beginAtZero
          />
          <Text tone="tertiary" size="small">
            Y-axis: wall time (ms). A zero bar means that series was not measured for
            the category (daemon is kscriptx-only; classic kscript has no daemon).
          </Text>
        </CardBody>
      </Card>

      <Stack gap={{8}}>
        <H2>Timing table</H2>
        <Table
          headers={{["Case", "Phase", "kscript", "kscriptx", "kscriptx daemon", "Speedup"]}}
          columnAlign={{["left", "left", "right", "right", "right", "right"]}}
          rows={{RESULT_ROWS}}
          striped
          stickyHeader
        />
        <Text tone="tertiary" size="small">
          Speedup = kscript_ms / kscriptx_ms for the same phase (higher means kscriptx is faster).
        </Text>
      </Stack>

      <Stack gap={{8}}>
        <H2>What each case measures</H2>
        <Table
          headers={{["Id", "Label", "Script", "Description"]}}
          rows={{CASE_ROWS}}
          striped
        />
      </Stack>

      <Stack gap={{8}}>
        <H2>Phase definitions</H2>
        <Table
          headers={{["Phase", "Meaning"]}}
          rows={{PHASE_ROWS}}
        />
      </Stack>

      <Callout tone="info" title="How to re-run">
        ./scripts/bench-compare.sh writes compare.json + compare.md and refreshes this canvas
        via scripts/gen-bench-canvas.py. Use --kscript PATH, --skip-kscript, --cases id1,id2,
        or --warm-runs N as needed.
      </Callout>

      <Divider />
      <Text tone="tertiary" size="small">
        {j(footer)}
      </Text>
    </Stack>
  );
}}
"""


def main() -> None:
    json_path = Path(sys.argv[1]) if len(sys.argv) > 1 else default_json()
    out_path = Path(sys.argv[2]) if len(sys.argv) > 2 else default_canvas()

    if not json_path.is_file():
        raise SystemExit(f"Missing {json_path}. Run ./scripts/bench-compare.sh first.")

    doc = json.loads(json_path.read_text(encoding="utf-8"))
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(build_tsx(doc), encoding="utf-8")
    print(f"Wrote {out_path}")


if __name__ == "__main__":
    main()
